=begin
#Alfresco Content Services REST API

#**Search API**  Provides access to the search features of Alfresco Content Services. 

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/content_info'
require 'swagger_client/models/error'
require 'swagger_client/models/generic_bucket'
require 'swagger_client/models/generic_facet_response'
require 'swagger_client/models/generic_metric'
require 'swagger_client/models/node'
require 'swagger_client/models/pagination'
require 'swagger_client/models/path_element'
require 'swagger_client/models/path_info'
require 'swagger_client/models/request_defaults'
require 'swagger_client/models/request_facet_field'
require 'swagger_client/models/request_facet_fields'
require 'swagger_client/models/request_facet_intervals'
require 'swagger_client/models/request_facet_queries'
require 'swagger_client/models/request_facet_set'
require 'swagger_client/models/request_fields'
require 'swagger_client/models/request_filter_queries'
require 'swagger_client/models/request_highlight'
require 'swagger_client/models/request_include'
require 'swagger_client/models/request_limits'
require 'swagger_client/models/request_localization'
require 'swagger_client/models/request_pagination'
require 'swagger_client/models/request_pivot'
require 'swagger_client/models/request_query'
require 'swagger_client/models/request_range'
require 'swagger_client/models/request_scope'
require 'swagger_client/models/request_sort_definition'
require 'swagger_client/models/request_spellcheck'
require 'swagger_client/models/request_stats'
require 'swagger_client/models/request_templates'
require 'swagger_client/models/response_consistency'
require 'swagger_client/models/result_buckets'
require 'swagger_client/models/result_node'
require 'swagger_client/models/result_set_context'
require 'swagger_client/models/result_set_paging'
require 'swagger_client/models/result_set_row_entry'
require 'swagger_client/models/search_entry'
require 'swagger_client/models/search_request'
require 'swagger_client/models/user_info'

# APIs
require 'swagger_client/api/search_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
